# Generated by Django 5.0.6 on 2025-09-11 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RawGameSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'captured_at'], name='ingest_rawg_provide_49df2b_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawOddsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('payload', models.JSONField()),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'captured_at'], name='ingest_rawo_provide_56c5ab_idx')],
            },
        ),
        migrations.CreateModel(
            name='TeamAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('team_name', models.CharField(max_length=100)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingest.provider')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'alias'], name='ingest_team_provide_4a2ba5_idx')],
                'unique_together': {('provider', 'alias')},
            },
        ),
    ]
