# Generated by Django 5.0.6 on 2025-09-10 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('conference', models.CharField(blank=True, max_length=10)),
                ('division', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField()),
                ('week', models.IntegerField()),
                ('kickoff', models.DateTimeField()),
                ('venue', models.CharField(blank=True, max_length=100)),
                ('roof', models.CharField(blank=True, max_length=20)),
                ('weather_temp', models.FloatField(blank=True, null=True)),
                ('weather_wind', models.FloatField(blank=True, null=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_games', to='games.team')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_games', to='games.team')),
            ],
        ),
        migrations.CreateModel(
            name='Odds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=50)),
                ('spread', models.FloatField(blank=True, null=True)),
                ('spread_price', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('total_price', models.IntegerField(blank=True, null=True)),
                ('moneyline_home', models.IntegerField(blank=True, null=True)),
                ('moneyline_away', models.IntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='odds', to='games.game')),
            ],
            options={
                'indexes': [models.Index(fields=['game', 'book', 'captured_at'], name='games_odds_game_id_dbc262_idx')],
            },
        ),
    ]
