# Generated by Django 5.0.6 on 2025-09-10 07:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parlay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='user', max_length=20)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('week', models.IntegerField(blank=True, null=True)),
                ('stake', models.FloatField(default=0.0)),
                ('combined_probability', models.FloatField(blank=True, null=True)),
                ('fair_odds_american', models.IntegerField(blank=True, null=True)),
                ('market_parlay_odds_american', models.IntegerField(blank=True, null=True)),
                ('expected_value', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParlayLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leg_type', models.CharField(max_length=20)),
                ('player_name', models.CharField(blank=True, max_length=100)),
                ('prop_type', models.CharField(blank=True, max_length=40)),
                ('line', models.FloatField(blank=True, null=True)),
                ('side', models.CharField(blank=True, max_length=20)),
                ('model_prob', models.FloatField()),
                ('market_odds_american', models.IntegerField()),
                ('leg_ev_at_1u', models.FloatField(blank=True, null=True)),
                ('game', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='games.game')),
                ('parlay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legs', to='parlays.parlay')),
            ],
        ),
    ]
